[package]
name = "polycube"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "canonicalize"
harness = false

[[bench]]
name = "generations"
harness = false

